name: Lint and Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly
    - uses: actions/checkout@master
    - name: Cache crates
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Clippy Lint
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
